# Generated by Django 3.0.3 on 2020-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200301_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=50),
        ),
    ]
