# Generated by Django 3.0.3 on 2020-03-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'EN'), ('kr', 'KR')], default='kr', max_length=2),
        ),
    ]
