# Generated by Django 3.0.3 on 2020-02-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='isinstance_book',
            new_name='instant_book',
        ),
    ]
