# Generated by Django 3.0.3 on 2020-02-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200212_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(null=True, upload_to='room_photos'),
        ),
    ]
